module.exports = ( ) => {
        genesis = require( `./_genesis.json` )
        exodus = require( `./_exodus.json` )
        leviticus = require( `./_leviticus.json` )
        numbers = require( `./_numbers.json` )
        deuteronomy = require( `./_deuteronomy.json` )
        joshua = require( `./_joshua.json` )
        judges = require( `./_judges.json` )
        ruth = require( `./_ruth.json` )
        Isamuel = require( `./_Isamuel.json` )
        IIsamuel = require( `./_IIsamuel.json` )
        Ikings = require( `./_Ikings.json` )
        IIkings = require( `./_IIkings.json` )
        Ichronicles = require( `./_Ichronicles.json` )
        IIchronicles = require( `./_IIchronicles.json` )
        ezra = require( `./_ezra.json` )
        nehemiah = require( `./_nehemiah.json` )
        esther = require( `./_esther.json` )
        job = require( `./_job.json` )
        psalms = require( `./_psalms.json` )
        proverbs = require( `./_proverbs.json` )
        ecclesiastes = require( `./_ecclesiastes.json` )
        songofsolomon = require( `./_songofsolomon.json` )
        isaiah = require( `./_isaiah.json` )
        jeremiah = require( `./_jeremiah.json` )
        lamentations = require( `./_lamentations.json` )
        ezekiel = require( `./_ezekiel.json` )
        daniel = require( `./_daniel.json` )
        hosea = require( `./_hosea.json` )
        joel = require( `./_joel.json` )
        amos = require( `./_amos.json` )
        obadiah = require( `./_obadiah.json` )
        jonah = require( `./_jonah.json` )
        micah = require( `./_micah.json` )
        nahum = require( `./_nahum.json` )
        habakkuk = require( `./_habakkuk.json` )
        zephaniah = require( `./_zephaniah.json` )
        haggai = require( `./_haggai.json` )
        zechariah = require( `./_zechariah.json` )
        malachi = require( `./_malachi.json` )
        matthew = require( `./_matthew.json` )
        mark = require( `./_mark.json` )
        luke = require( `./_luke.json` )
        john = require( `./_john.json` )
        acts = require( `./_acts.json` )
        romans = require( `./_romans.json` )
        Icorinthians = require( `./_Icorinthians.json` )
        IIcorinthians = require( `./_IIcorinthians.json` )
        galatians = require( `./_galatians.json` )
        ephesians = require( `./_ephesians.json` )
        philippians = require( `./_philippians.json` )
        colossians = require( `./_colossians.json` )
        Ithessalonians = require( `./_Ithessalonians.json` )
        IIthessalonians = require( `./_IIthessalonians.json` )
        Itimothy = require( `./_Itimothy.json` )
        IItimothy = require( `./_IItimothy.json` )
        titus = require( `./_titus.json` )
        philemon = require( `./_philemon.json` )
        hebrews = require( `./_hebrews.json` )
        james = require( `./_james.json` )
        Ipeter = require( `./_Ipeter.json` )
        IIpeter = require( `./_IIpeter.json` )
        Ijohn = require( `./_Ijohn.json` )
        IIjohn = require( `./_IIjohn.json` )
        IIIjohn = require( `./_IIIjohn.json` )
        jude = require( `./_jude.json` )
        revelation = require( `./_revelation.json` )
        
        return {
            books: {
                genesis,exodus,leviticus,numbers,deuteronomy,joshua,judges,ruth,Isamuel,IIsamuel,Ikings,IIkings,Ichronicles,IIchronicles,ezra,nehemiah,esther,job,psalms,proverbs,ecclesiastes,songofsolomon,isaiah,jeremiah,lamentations,ezekiel,daniel,hosea,joel,amos,obadiah,jonah,micah,nahum,habakkuk,zephaniah,haggai,zechariah,malachi,matthew,mark,luke,john,acts,romans,Icorinthians,IIcorinthians,galatians,ephesians,philippians,colossians,Ithessalonians,IIthessalonians,Itimothy,IItimothy,titus,philemon,hebrews,james,Ipeter,IIpeter,Ijohn,IIjohn,IIIjohn,jude,revelation
            },
            data:{language:"fi", version: "Finnish"}
        }
        
    }