module.exports = ( ) => {
        genesis = require( `./_genesis.json` )
        exodo = require( `./_exodo.json` )
        levitico = require( `./_levitico.json` )
        numeros = require( `./_numeros.json` )
        deuteronomio = require( `./_deuteronomio.json` )
        josue = require( `./_josue.json` )
        juizes = require( `./_juizes.json` )
        rute = require( `./_rute.json` )
        Isamuel = require( `./_Isamuel.json` )
        IIsamuel = require( `./_IIsamuel.json` )
        Ireis = require( `./_Ireis.json` )
        IIreis = require( `./_IIreis.json` )
        Icronicas = require( `./_Icronicas.json` )
        IIcronicas = require( `./_IIcronicas.json` )
        esdras = require( `./_esdras.json` )
        neemias = require( `./_neemias.json` )
        ester = require( `./_ester.json` )
        jo = require( `./_jo.json` )
        salmos = require( `./_salmos.json` )
        proverbios = require( `./_proverbios.json` )
        eclesiastes = require( `./_eclesiastes.json` )
        canticos = require( `./_canticos.json` )
        isaias = require( `./_isaias.json` )
        jeremias = require( `./_jeremias.json` )
        lamentacoesdejeremias = require( `./_lamentacoesdejeremias.json` )
        ezequiel = require( `./_ezequiel.json` )
        daniel = require( `./_daniel.json` )
        oseias = require( `./_oseias.json` )
        joel = require( `./_joel.json` )
        amos = require( `./_amos.json` )
        obadias = require( `./_obadias.json` )
        jonas = require( `./_jonas.json` )
        miqueias = require( `./_miqueias.json` )
        naum = require( `./_naum.json` )
        habacuque = require( `./_habacuque.json` )
        sofonias = require( `./_sofonias.json` )
        ageu = require( `./_ageu.json` )
        zacarias = require( `./_zacarias.json` )
        malaquias = require( `./_malaquias.json` )
        mateus = require( `./_mateus.json` )
        marcos = require( `./_marcos.json` )
        lucas = require( `./_lucas.json` )
        joao = require( `./_joao.json` )
        atos = require( `./_atos.json` )
        romanos = require( `./_romanos.json` )
        Icorintios = require( `./_Icorintios.json` )
        IIcorintios = require( `./_IIcorintios.json` )
        galatas = require( `./_galatas.json` )
        efesios = require( `./_efesios.json` )
        filipenses = require( `./_filipenses.json` )
        colossenses = require( `./_colossenses.json` )
        Itessalonicenses = require( `./_Itessalonicenses.json` )
        IItessalonicenses = require( `./_IItessalonicenses.json` )
        Itimoteo = require( `./_Itimoteo.json` )
        IItimoteo = require( `./_IItimoteo.json` )
        tito = require( `./_tito.json` )
        filemom = require( `./_filemom.json` )
        hebreus = require( `./_hebreus.json` )
        tiago = require( `./_tiago.json` )
        Ipedro = require( `./_Ipedro.json` )
        IIpedro = require( `./_IIpedro.json` )
        Ijoao = require( `./_Ijoao.json` )
        IIjoao = require( `./_IIjoao.json` )
        IIIjoao = require( `./_IIIjoao.json` )
        judas = require( `./_judas.json` )
        apocalipse = require( `./_apocalipse.json` )
        
        return {
            books: {
                genesis,exodo,levitico,numeros,deuteronomio,josue,juizes,rute,Isamuel,IIsamuel,Ireis,IIreis,Icronicas,IIcronicas,esdras,neemias,ester,jo,salmos,proverbios,eclesiastes,canticos,isaias,jeremias,lamentacoesdejeremias,ezequiel,daniel,oseias,joel,amos,obadias,jonas,miqueias,naum,habacuque,sofonias,ageu,zacarias,malaquias,mateus,marcos,lucas,joao,atos,romanos,Icorintios,IIcorintios,galatas,efesios,filipenses,colossenses,Itessalonicenses,IItessalonicenses,Itimoteo,IItimoteo,tito,filemom,hebreus,tiago,Ipedro,IIpedro,Ijoao,IIjoao,IIIjoao,judas,apocalipse
            },
            data:{language:"pt-br", version: "AA"}
        }
        
    }